//! Function-style tools generated by `#[agentyk::tool]`.

use agentyk::{Agent, ModelSpec, SimDriver, SimTurn, Tool, ToolContext, ToolOutput};
use serde::Deserialize;
use serde_json::json;

#[derive(Deserialize, agentyk::JsonSchema)]
struct Location {
    city: String,
}

#[agentyk::tool(description = "Add two integers.")]
async fn add(a: i64, b: i64) -> ToolOutput {
    ToolOutput::text((a + b).to_string())
}

#[agentyk::tool(name = "session", description = "Return the current session id.")]
async fn current_session(context: &ToolContext) -> ToolOutput {
    ToolOutput::text(context.session_id.to_string())
}

#[agentyk::tool(description = "Greet someone, if supplied.")]
async fn greet(name: Option<String>) -> ToolOutput {
    ToolOutput::text(name.unwrap_or_else(|| "world".to_owned()))
}

#[agentyk::tool(description = "Return a weather report.")]
async fn weather(location: Location) -> ToolOutput {
    ToolOutput::text(format!("sunny in {}", location.city))
}

#[test]
fn macro_builds_definition_from_function_signature() {
    let definition = add.definition();

    assert_eq!(definition.name, "add");
    assert_eq!(definition.description, "Add two integers.");
    assert_eq!(definition.parameters["type"], "object");
    assert_eq!(definition.parameters["properties"]["a"]["type"], "integer");
    assert_eq!(definition.parameters["properties"]["b"]["type"], "integer");
    assert_eq!(definition.parameters["required"], json!(["a", "b"]));
}

#[test]
fn custom_parameter_schemas_keep_their_definitions_at_the_root() {
    let parameters = weather.definition().parameters;

    assert_eq!(
        parameters["properties"]["location"]["$ref"],
        "#/$defs/Location"
    );
    assert_eq!(parameters["$defs"]["Location"]["type"], "object");
}

#[tokio::test]
async fn macro_deserializes_arguments_and_reports_bad_input() {
    let context = ToolContext::default();

    let output = add.execute(json!({"a": 2, "b": 3}), &context).await;
    assert_eq!(output, ToolOutput::text("5"));

    let output = add.execute(json!({"a": 2}), &context).await;
    assert!(output.is_error);
    assert_eq!(output.content, "missing required argument `b`");
}

#[tokio::test]
async fn option_parameters_can_be_omitted() {
    let definition = greet.definition();
    assert_eq!(definition.parameters["required"], json!([]));

    let output = greet.execute(json!({}), &ToolContext::default()).await;
    assert_eq!(output, ToolOutput::text("world"));
}

#[tokio::test]
async fn macro_passes_tool_context_without_exposing_it_to_model() {
    let context = ToolContext::default();
    let output = current_session.execute(json!({}), &context).await;

    assert_eq!(output.content, context.session_id.to_string());
    assert_eq!(
        current_session.definition().parameters["properties"],
        json!({})
    );
}

#[tokio::test]
async fn generated_tool_attaches_directly_to_agent_builder() -> agentyk::Result<()> {
    let agent = Agent::builder()
        .model(ModelSpec::llmsim())
        .driver(SimDriver::new([
            SimTurn::tool_call("add", json!({"a": 2, "b": 3})),
            SimTurn::text("five"),
        ]))
        .tool(add)
        .build()?;

    let turn = agent.session().run("add two and three").await?;
    assert_eq!(turn.response, "five");
    assert_eq!(turn.tool_calls, 1);
    Ok(())
}
